extends:
  - ../../.eslintrc.production.yml
  - ../../.eslintrc.react.yml

# TODO: #3212 When we move to React Native, we should disable this.
env:
  browser: true

rules:
  react/destructuring-assignment: off
  react/require-default-props: off
  dot-notation: off
