extends:
  - ../../.eslintrc.production.yml
  - ../../.eslintrc.react.yml

# TODO: #3212 When we move to React Native, we should disable this.
env:
  browser: true

rules:
  react/destructuring-assignment: off
  react/require-default-props: off
  no-restricted-imports:
    - error
    - patterns:
      - group:
        - botframework-webchat-*
        - '!botframework-webchat-base' # It is okay to import from private packages.
        - '!botframework-webchat-react-valibot' # It is okay to import from private packages.
        - '!botframework-webchat-styles' # It is okay to import from private packages.
        message: Imports only from "bundle" package but not other packages under it
