export {
  buildInfo,
  Components,
  concatMiddleware,
  Constants,
  createBrowserWebSpeechPonyfillFactory,
  createStore,
  createStoreWithDevTools,
  createStoreWithOptions,
  createStyleSet,
  decorator,
  hooks,
  internal,
  ReactWebChat,
  renderWebChat,
  testIds,
  version,
  withEmoji,
  type StrictStyleOptions,
  type StyleOptions
} from './package-preset/boot/actual/minimal';
