env:
  node: true

extends:
- ./.eslintrc.yml

rules:
  # Node.js and CommonJS eslint-plugin-node
  node/callback-return: error
  node/global-require: error
  node/handle-callback-err: error
  node/no-mixed-requires: error
  node/no-new-require: error
  node/no-path-concat: error
  node/no-sync: error
  node/no-missing-import:
    - error
    - tryExtensions:
        - ".js"
        - ".json"
        - ".node"
        - ".ts"
  node/no-unpublished-import: off
  node/prefer-global/buffer: error
