version: '3'

services:
  # On Windows, run with COMPOSE_CONVERT_WINDOWS_PATHS=1

  chrome:
    build:
      context: ./
      dockerfile: chrome.dockerfile
    depends_on:
      - selenium-hub
      - webchat
      - webchat2
    environment:
      HUB_HOST: selenium-hub
      HUB_PORT: '4444'
      # SE_EVENT_BUS_HOST: selenium-hub
      # SE_EVENT_BUS_PUBLISH_PORT: '4442
      # SE_EVENT_BUS_SUBSCRIBE_PORT: '4443'
      # SE_OPTS: '--log-level WARNING'
      # SE_NODE_SESSION_TIMEOUT: '300'
    shm_size: '2.5gb'

  selenium-hub:
    image: selenium/hub:3.141.59-zirconium
    # image: selenium/hub:4.0.0-beta-3-20210426
    container_name: selenium-hub
    environment:
      GRID_TIMEOUT: '300'
    ports:
      - '4444:4444'

  webchat:
    build:
      context: ./
      dockerfile: testharness.dockerfile
    ports:
      - '5080:80'
    stop_grace_period: 0s

  webchat2:
    build:
      context: ./
      dockerfile: testharness2.dockerfile
    ports:
      - '5081:80'
    stop_grace_period: 0s
    volumes:
      - ./__tests__/html/:/var/web/__tests__/html/
      - ./packages/bundle/dist/:/var/web/packages/bundle/dist/
      - ./packages/test/harness/dist/:/var/web/packages/test/harness/dist/
      - ./packages/test/page-object/dist/:/var/web/packages/test/page-object/dist/

  jest-server:
    build:
      context: ./packages/test/harness/
    ports:
      - '4445:4445'
    stop_grace_period: 5s
