const CustomPropertyNames = Object.freeze({
  // Make sure key names does not have JavaScript forbidden names.
  BackgroundCodeBlock: '--webchat__background--code-block',
  BorderAnimationColor1: '--webchat__border-animation--color-1',
  BorderAnimationColor2: '--webchat__border-animation--color-2',
  BorderAnimationColor3: '--webchat__border-animation--color-3',
  ColorAccent: '--webchat__color--accent',
  ColorCodeBlock: '--webchat__color--code-block',
  ColorSubtle: '--webchat__color--subtle',
  ColorTimestamp: '--webchat__color--timestamp',
  FontPrimary: '--webchat__font--primary',
  FontSizeSmall: '--webchat__font-size--small',
  IconURLExternalLink: '--webchat__icon-url--external-link',
  MaxHeightImageBubble: '--webchat__max-height--image-bubble',
  MaxWidthAttachmentBubble: '--webchat__max-width--attachment-bubble',
  MaxWidthMessageBubble: '--webchat__max-width--message-bubble',
  MinHeightBubble: '--webchat__min-height--bubble',
  MinHeightImageBubble: '--webchat__min-height--image-bubble',
  MinWidthAttachmentBubble: '--webchat__min-width--attachment-bubble',
  MinWidthMessageBubble: '--webchat__min-width--message-bubble',
  PaddingRegular: '--webchat__padding--regular',
  SizeAvatar: '--webchat__size--avatar',
  FeedbackFormFont: '--webchat__font--primary',
  FeedbackFormTitleColor: '--webchat__font--color-primary',
  FeedbackFormDisclaimerColor: '--webchat__font--color-secondary',
  FeedbackFormSubmitButtonColor: '--webchat__color--accent',
  FeedbackFormSubmitButtonFontColor: '--webchat__button--text--primary',
  FeedbackFormSubmitButtonHoverColor: '--webchat__button--primary--hover',
  FeedbackFormSubmitButtonActiveColor: '--webchat__button--primary--active',
  FeedbackFormSubmitButtonDisabledColor: '--webchat__button--primary--disabled',
  FeedbackFormCancelButtonColor: '--webchat__button--secondary',
  FeedbackFormCancelButtonFontColor: '--webchat__button--text--secondary',
  FeedbackFormCancelButtonBorderColor: '--webchat__button--secondary-border',
  FeedbackFormCancelButtonHoverColor: '--webchat__button--secondary--hover',
  FeedbackFormSendBoxBackgroundColor: '--webchat__textbox--background',
  FeedbackFormSendBoxBorderColor: '--webchat__textbox--border',
  FeedbackFormSendBoxFontColor: '--webchat__button--text--secondary',
  FeedbackFormSendBoxFocusBorderColor: '--webchat__textbox--border--focus',
  FeedbackFormSendBoxActiveBorderColor: '--webchat__textbox--border--selected',
  FeedbackFormSendBoxMinHeight: '--webchat__textbox--min-height',
  FeedbackFormSendBoxMinWidth: '--webchat__textbox--min-width',
  FeedbackFormSendBoxPadding: '--webchat__textbox--padding'
}) satisfies Readonly<Record<string, `--webchat__${string}`>>;

export default CustomPropertyNames;
