extends:
  - ../../.eslintrc.production.yml
  - ../../.eslintrc.react.yml

# This package is expected to run inside a web browser.
env:
  browser: true

rules:
  no-restricted-imports:
    - error
    - patterns:
        - group:
            - '@msinternal/botframework-webchat-api-*'
          message: 'To prevent duplicated import, @msinternal/botframework-webchat-api-* is only allowed to import in botframework-webchat-api.'
