name: Accessibility issue
description: Create a report to help us improve the accessibility experience.
labels:
  - area-accessibility
  - bug
  - customer-reported
  - Bot Services
body:
  - type: markdown
    attributes:
      value: |
        > Please view our [accessibility guide](https://github.com/microsoft/BotFramework-WebChat/tree/main/docs/ACCESSIBILITY.md) before filing a new issue.
        >
        > Be sure to remove or obscure personally identifiable information from your code and screenshots.
  - type: dropdown
    attributes:
      label: Is it an issue related to Adaptive Cards?
      description: If yes, please verify if this issue repro on [Adaptive Cards Designer](https://adaptivecards.io/designer/). If it repro on their designer, please [file an issue to their repository](https://github.com/microsoft/AdaptiveCards/issues/new/choose).
      options:
        - ""
        - Yes, this is related to Adaptive Card. However, it does not repro on Adaptive Cards Designer.
        - "No."
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: What is the impact?
  - type: dropdown
    id: test-environment
    attributes:
      label: What browsers and screen readers do this issue affect?
      description: Please make sure the issue continued to repro on latest version of the browser and screen reader. If you choose "Others", please provide us information in the additional context section.
      multiple: true
      options:
        - "Windows: Edge with Windows Narrator"
        - "Windows: Chrome with NVDA"
        - "Windows: Chrome/Firefox with JAWS"
        - "macOS: Safari with VoiceOver"
        - "iOS/iPadOS: Safari with VoiceOver"
        - "Android: Chrome with TalkBack"
        - "Others"
  - type: dropdown
    attributes:
      label: Are there any code-based customization done to Web Chat?
      description: |
        If customization is done solely using `styleOptions`, please answer "No".

        Code-based customization might affect how Web Chat works with screen readers. Please verify if this issue continue to repro without any code-based customization.
      options:
        - No, I am using Web Chat without any customizations except "styleOptions".
        - Yes, however, this also repro when customizations are removed.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: What version of Web Chat are you using?
      description: |
        To determine what version of Web Chat you are running, open your browser's development tools, and paste the following line of code into the console.

        `[].map.call(document.head.querySelectorAll('meta[name^="botframework-"]'), function (meta) { return meta.outerHTML; }).join('\n')`

        The latest version number of Web Chat can be found in the [Releases section](https://github.com/microsoft/BotFramework-WebChat/releases/latest).

        If you are not using latest version of Web Chat, please upgrade to the latest version as the issue may had resolved.
      options:
        - Latest production
        - Development build
        - I am not using latest
        - Unrelated
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Which area does this issue affect?
      multiple: true
      options:
        - ARIA roles
        - Contrast ratio
        - Focus management
        - Forced colors (high contrast mode)
        - Keyboard focus indicator
        - Keyboard navigation
        - Live region
        - Send box
        - Suggested action
        - Transcript navigation
        - Others or unrelated
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: What is the public URL for the website?
      description: If the bot is not intended for public use, please leave this blank. It will be helpful if we can test the bot to understand the issue.
      placeholder: "https://"
  - type: textarea
    id: repro-steps
    attributes:
      label: How to reproduce the issue?
      value: |
        1. Navigate to ...
        2. Type "..." in the send box
        3. Press <kbd>TAB</kbd> to ...
    validations:
      required: true
  - type: textarea
    id: expected-result
    attributes:
      label: What do you expect?
      description: Give a clear and concise description of what you expect to happen.
    validations:
      required: true
  - type: textarea
    id: actual-result
    attributes:
      label: What actually happened?
      description: Give a clear and concise description of what actually happened.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Do you have any screenshots or recordings to repro the issue?
      description: Be sure to remove or obscure personally identifiable information from your code and screenshots.
  - type: textarea
    id: dom-element
    attributes:
      label: Did you find any DOM elements that might have caused the issue?
      description: If yes, please paste a screenshot or its code below. Knowing the suspected DOM element could greatly reduce our time on investigating and resolving the issue.
  - type: input
    id: mas-reference
    attributes:
      label: MAS reference
      description: For internal use only. Please link to MAS documentation, if any.
      placeholder: https://microsoft.sharepoint.com/:w:/s/accessibility/
  - type: input
    id: wcag-reference
    attributes:
      label: WCAG reference
      description: Please link to related criterion from the [Understanding WCAG](https://www.w3.org/WAI/WCAG21/Understanding/) article.
      placeholder: https://www.w3.org/WAI/WCAG21/Understanding/
  - type: input
    id: wai-aria-reference
    attributes:
      label: WAI-ARIA reference
      description: For roles, state, and properties issues, please link to their related section from the [Accessible Rich Internet Applications (WAI-ARIA)](https://www.w3.org/TR/wai-aria/) article.
      placeholder: https://www.w3.org/TR/wai-aria/
  - type: textarea
    id: adaptive-card-json
    attributes:
      label: Adaptive Card JSON
      description: |
        If this issue is related to Adaptive Cards, please paste the JSON of the card below.

        Please verify if this issue repro on [Adaptive Cards Designer](https://adaptivecards.io/designer/). If it repro on their designer, please [file an issue to their repository](https://github.com/microsoft/AdaptiveCards/issues/new/choose).
      placeholder: |
        {
          "type": "AdaptiveCard",
          "body": []
          "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
          "version": "1.5"
        }
      render: json
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here. If you have any screenshots or recordings, please include it here.
