env:
  browser: true

overrides:
  - files:
      # This is loader for Jest to support ESM.
      - '*.spec.js'
      # This is run during "postinstall", and is for Node.js
      - 'src/install.js'
    env:
      node: true
