env:
  shared-node-browser: true

parserOptions:
  sourceType: module

overrides:
  - files:
      # This is loader for Jest to support ESM.
      - '*.spec.js'
      # This is run during "postinstall", and is for Node.js
      - 'src/install.mjs'
    extends:
      - '../../../.eslintrc.node.yml'

  - files:
      # This is loader for Jest to support ESM.
      - '*.spec.js'
    extends:
      - plugin:node/recommended-script
