FROM node:12 AS builder-web
EXPOSE 80
WORKDIR /var/
ADD build.tgz /var/
ADD .env.bot /var/bot/
ADD .env.web /var/web/

ENTRYPOINT ./node_modules/.bin/concurrently --kill-others --names "bot,web" "node bot" "node rest-api"
