# Based on Node.js 12 image
FROM node:12

# Expose port 80 and set entrypoint
EXPOSE 80
WORKDIR /var/bot/
ENTRYPOINT node .

# Set environment variable NODE_ENV to "production"
ENV NODE_ENV production

# Copy the bot code to /var/bot/
# We excluded /.env and /node_modules/ via .dockerignore
ADD bot/ /var/bot/

# Doing a fresh "npm install" on build to make sure the image is reproducible
RUN npm ci
