FROM node:12 AS builder
WORKDIR /var/web/

ADD app/ /var/web/
RUN npm ci
RUN npm run build

FROM node:12
EXPOSE 80
WORKDIR /var/web/
ENTRYPOINT node .
ENV NODE_ENV production
ADD rest-api/ /var/web/
COPY --from=builder /var/web/build/ /var/web/public
RUN npm ci
