extends:
  - ../../.eslintrc.production.yml
  - ../../.eslintrc.react.yml

# TODO: #3212 When we move to React Native, we should disable this.
env:
  browser: true

rules:
  no-restricted-imports:
    - error
    - message: 'To prevent duplicated import, @msinternal/botframework-webchat-middleware is only allowed to import in botframework-webchat-api.'
      name: '@msinternal/botframework-webchat-middleware'
