version: "3.7"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile-bot
    env_file: ./bot/.env
    # image: your-own-registry.azurecr.io/webchat-sso-intranet-bot
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    env_file: ./web/.env
    # image: your-own-registry.azurecr.io/webchat-sso-intranet-web
    ports:
      - "3000:5000"
