/// <reference types="react" />
import * as React from 'react';
import { BehaviorSubject } from 'rxjs/BehaviorSubject';
import { Activity, CardActionTypes, DirectLineOptions, IBotConnection, User } from 'botframework-directlinejs';
import { SpeechOptions } from './SpeechOptions';
import { WindowState } from './Store';
import { ActivityOrID, FormatOptions } from './Types';
export interface ChatProps {
    adaptiveCardsHostConfig: any;
    bot: User;
    botConnection?: IBotConnection;
    chatTitle?: boolean | string;
    directLine?: DirectLineOptions;
    disabled?: boolean;
    formatOptions?: FormatOptions;
    locale?: string;
    history?: () => Promise<Activity[]>;
    resize?: 'none' | 'window' | 'detect';
    selectedActivity?: BehaviorSubject<ActivityOrID>;
    sendTyping?: boolean;
    showUploadButton?: boolean;
    speechOptions?: SpeechOptions;
    user: User;
    botIconUrl: string;
    chatIconColor: string;
    chatIconMessage?: string;
    showBrandMessage: boolean;
    brandMessage: string;
    windowStatus: WindowState;
    hideHeader: boolean;
}
export declare class Chat extends React.Component<ChatProps, {}> {
    private store;
    private user;
    private botConnection;
    private activitySubscription;
    private connectionStatusSubscription;
    private selectedActivitySubscription;
    private shellRef;
    private historyRef;
    private chatviewPanelRef;
    private firstLoad;
    private showChatIconMessage;
    private resizeListener;
    private _handleCardAction;
    private _handleKeyDownCapture;
    private _saveChatviewPanelRef;
    private _saveHistoryRef;
    private _saveShellRef;
    private hasHistory;
    getUser(): {
        id: string;
        name?: string;
        iconUrl?: string;
        role?: "bot" | "user" | "channel";
    };
    constructor(props: ChatProps);
    private handleIncomingActivity(activity);
    private setSize();
    private handleCardAction();
    private handleKeyDownCapture(evt);
    private saveChatviewPanelRef(chatviewPanelRef);
    private saveHistoryRef(historyWrapper);
    private saveShellRef(shellWrapper);
    startConnection(): void;
    componentWillMount(): void;
    componentDidMount(): void;
    componentWillUnmount(): void;
    componentWillReceiveProps(nextProps: ChatProps): void;
    onClickChatIcon(): void;
    onCloseWindow(): void;
    onCloseChatMessage(): void;
    render(): JSX.Element;
}
export declare type IDoCardAction = (type: CardActionTypes, value: string | object) => void;
export declare const doCardAction: (botConnection: IBotConnection, from: User, locale: string, sendMessage: (value: string, user: User, locale: string) => void) => IDoCardAction;
export declare const sendPostBack: (botConnection: IBotConnection, text: string, value: object, from: User, locale: string) => void;
export declare const sendEventPostBack: (botConnection: IBotConnection, name: string, value: object, from: User) => void;
export declare const renderIfNonempty: (value: any, renderer: (value: any) => JSX.Element) => JSX.Element;
export declare const classList: (...args: (string | boolean)[]) => string;
