#!/bin/bash

cd samples/breakaway-speech-button
npm run build

cd ../../samples/minimize-mode
npm run build

cd ../../samples/redux-activity-middleware
npm run build

cd ../../
rsync -av --progress samples/ gh-pages/ --exclude backend-cli --exclude breakaway-speech-button --exclude minimize-mode --exclude redux-activity-middleware

mkdir gh-pages/breakaway-speech-button
rsync -av --progress samples/breakaway-speech-button/build/ gh-pages/breakaway-speech-button/

mkdir gh-pages/minimize-mode
rsync -av --progress samples/minimize-mode/build/ gh-pages/minimize-mode/

mkdir gh-pages/redux-activity-middleware
rsync -av --progress samples/redux-activity-middleware/build/ gh-pages/redux-activity-middleware/
