#!/bin/bash

rsync -av --progress samples/ gh-pages/ \
  --exclude 06.recomposing-UI/a.minimizable-web-chat \
  --exclude 06.recomposing-UI/b.speech-ui \
  --exclude  06.recomposing-UI/c.smart-display \
  --exclude 04.API/e.piping-to-redux \
  --exclude 04.API/f.selectable-activity \
  --exclude 04.API/g.chat-send-history \
  --exclude 04.API/h.clear-after-idle \
  --exclude 21.customization-plain-ui

mkdir gh-pages/06.recomposing-UI/a.minimizable-web-chat
rsync -av --progress samples/06.recomposing-UI/a.minimizable-web-chat/build/ gh-pages/06.recomposing-UI/a.minimizable-web-chat/

mkdir gh-pages/06.recomposing-UI/b.speech-ui
rsync -av --progress samples/06.recomposing-UI/b.speech-ui/build/ gh-pages/06.recomposing-UI/b.speech-ui/

mkdir gh-pages/ 06.recomposing-UI/c.smart-display
rsync -av --progress samples/ 06.recomposing-UI/c.smart-display/build/ gh-pages/ 06.recomposing-UI/c.smart-display/

mkdir gh-pages/04.API/e.piping-to-redux
rsync -av --progress samples/04.API/e.piping-to-redux/build/ gh-pages/04.API/e.piping-to-redux/

mkdir gh-pages/04.API/f.selectable-activity
rsync -av --progress samples/04.API/f.selectable-activity/build/ gh-pages/04.API/f.selectable-activity/

mkdir gh-pages/04.API/g.chat-send-history
rsync -av --progress samples/04.API/g.chat-send-history/build/ gh-pages/04.API/g.chat-send-history/

mkdir gh-pages/04.API/h.clear-after-idle
rsync -av --progress samples/04.API/h.clear-after-idle/build/ gh-pages/04.API/h.clear-after-idle/

mkdir gh-pages/21.customization-plain-ui
rsync -av --progress samples/21.customization-plain-ui/build/ gh-pages/21.customization-plain-ui/
