#!/bin/bash

echo //registry.npmjs.org/:_authToken=\${NPM_TOKEN} > ~/.npmrc

# If TRAVIS_TAG is present, it means this is going PRODUCTION
if [ -n "$TRAVIS_TAG" ]
then
  cd packages/core
  npm publish

  cd ../component
  npm publish

  cd ../bundle
  npm publish
fi

# If on "preview" branch, deploy to "preview" tag
if [ "$TRAVIS_BRANCH" = "preview" ]
then
  cd packages/core
  npm publish --tag preview

  cd ../component
  npm publish --tag preview

  cd ../bundle
  npm publish --tag preview
fi
