name: playground

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/playground.yaml
      - packages/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out for ${{ github.ref }}
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - run: npm clean-install --ignore-scripts

      - run: |
          npm run build
          cd packages/playground
          npm run build
          mkdir wwwroot
          mv build wwwroot
          cp host/* wwwroot
          cd wwwroot
          npm ci
          zip -1rq ../build.zip .
        env:
          NODE_ENV: production

      - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
          name: wwwroot
          path: packages/playground/build.zip

      - id: deploy
        uses: azure/webapps-deploy@2d85376f88b09cd11575b3d7e96b65c3effe5e05 # v2.1.2
        with:
          app-name: webchat-playground
          slot-name: production
          publish-profile: ${{ secrets.PLAYGROUND_PUBLISH_PROFILE }}
          package: packages/playground/build.zip

      - name: Ping deployment
        run: |
          sleep 15
          curl -s ${{ steps.deploy.outputs.webapp-url }}
