name: samples/07.d.sso-for-teams

on:
  workflow_dispatch: {} # Pipeline is disabled

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - .github/workflows/samples.07.d.sso-for-teams.yaml
#       - samples/07.advanced-web-chat-apps/d.sso-for-teams/**

env:
  APP_NAME: webchat-samples-ssoteams
  # DOCKER_IMAGE: your-own-registry.azurecr.io/webchat-samples-ssoteams
  # DOCKER_REGISTRY: your-own-registry.azurecr.io
  DOCKER_TAG: sha-${{ github.sha }}
  DOCKERFILE_PATH: samples/07.advanced-web-chat-apps/d.sso-for-teams
  PUBLISH_PROFILE: ${{ secrets.SAMPLES_SSOTEAMS_PUBLISH_PROFILE }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out for ${{ github.ref }}
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: Read variables
        id: variables
        run: |
          echo "::set-output name=short_sha::${GITHUB_SHA:0:7}"

      - uses: azure/docker-login@83efeb77770c98b620c73055fbb59b2847e17dc0 # v1.0.1
        with:
          login-server: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.SAMPLES_DOCKER_USERNAME }}
          password: ${{ secrets.SAMPLES_DOCKER_PASSWORD }}

      - name: Build and publish the image
        run: |
          cd ${{ env.DOCKERFILE_PATH }}
          docker build . -t builder
          docker create --name builder-image builder
          docker cp builder-image:/var/build/build.tgz .
          docker rm builder-image
          docker build . -f Dockerfile-run -t ${{ env.DOCKER_IMAGE }}:latest -t ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
          docker push ${{ env.DOCKER_IMAGE }}:latest
          docker push ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

      - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
          name: build
          path: ${{ env.DOCKERFILE_PATH }}/build.tgz

      - name: Publish to ${{ env.APP_NAME }}
        uses: azure/webapps-deploy@v2.1
        with:
          app-name: ${{ env.APP_NAME }}
          images: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
          publish-profile: ${{ env.PUBLISH_PROFILE }}
